const TodoActionTypes = {
  CREATE_TODO_START: "CREATE_TODO_START",
  CREATE_TODO_SUCCESS: "CREATE_TODO_SUCCESS",
  CREATE_TODO_FAILURE: "CREATE_TODO_FAILURE",
  READ_TODOS_START: "READ_TODOS_START",
  READ_TODOS_SUCCESS: "READ_TODOS_SUCCESS",
  READ_TODOS_FAILURE: "READ_TODOS_FAILURE",
  UPDATE_TODO_START: "UPDATE_TODO_START",
  UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
  UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE",
  DELETE_TODO_START: "DELETE_TODO_START",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",
};

export default TodoActionTypes;
